// 100 Balloon-Themed Website Designs
// Each theme controls: nav style, colors, fonts, hero style, section style, footer style, decorative elements

export const THEMES = [
  // ===== KIDS / BIRTHDAY =====
  {
    id: 'rainbow_birthday',
    name: 'Rainbow Birthday',
    category: 'kids',
    emoji: '🎈',
    description: 'Bright rainbow colors, playful fonts, confetti everywhere',
    preview: ['#ff6b6b','#feca57','#48dbfb'],
    css: {
      '--primary': '340 82% 52%',
      '--secondary': '45 100% 60%',
      '--accent': '180 70% 48%',
      '--background': '0 0% 100%',
      '--foreground': '260 20% 16%',
      '--font-display': "'Fredoka One', cursive",
      '--font-body': "'Nunito', sans-serif",
    },
    nav: {
      style: 'pill',
      bg: 'linear-gradient(135deg, #ff6b6b, #feca57, #48dbfb)',
      textColor: '#fff',
      logoColor: '#fff',
    },
    hero: {
      style: 'confetti',
      bg: 'linear-gradient(135deg, #ff6b6b 0%, #feca57 50%, #ff9ff3 100%)',
      pattern: 'dots',
    },
    footer: {
      bg: '#1a0030',
      textColor: '#fff',
      accent: '#feca57',
    },
    decorations: ['🎈','🎉','🎊','🎀','✨'],
    borderRadius: '2rem',
    buttonStyle: 'rounded-full font-bold shadow-lg',
  },
  {
    id: 'neon_party',
    name: 'Neon Party',
    category: 'kids',
    emoji: '⚡',
    description: 'Electric neon colors on dark background, high energy',
    preview: ['#0d0221','#ff00ff','#00ffff'],
    css: {
      '--primary': '300 100% 50%',
      '--secondary': '180 100% 50%',
      '--accent': '60 100% 50%',
      '--background': '270 90% 5%',
      '--foreground': '0 0% 95%',
    },
    nav: { style: 'glassmorphism', bg: 'rgba(13,2,33,0.8)', textColor: '#ff00ff', logoColor: '#00ffff' },
    hero: { style: 'neon', bg: 'linear-gradient(135deg, #0d0221 0%, #1a0050 50%, #0d0221 100%)', pattern: 'stars' },
    footer: { bg: '#0d0221', textColor: '#fff', accent: '#ff00ff' },
    decorations: ['⚡','🌈','💎','🔥','✨'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded-md font-bold border-2 border-current',
  },
  {
    id: 'cartoon_pop',
    name: 'Cartoon Pop',
    category: 'kids',
    emoji: '🫧',
    description: 'Bold outlines, primary colors, comic-style layouts',
    preview: ['#fff200','#ff4500','#0066ff'],
    css: {
      '--primary': '25 100% 50%',
      '--secondary': '60 100% 50%',
      '--accent': '220 100% 50%',
      '--background': '60 100% 97%',
      '--foreground': '0 0% 5%',
    },
    nav: { style: 'banner', bg: '#fff200', textColor: '#0066ff', logoColor: '#ff4500' },
    hero: { style: 'bold', bg: 'linear-gradient(90deg, #fff200, #ff4500)', pattern: 'dots' },
    footer: { bg: '#0066ff', textColor: '#fff', accent: '#fff200' },
    decorations: ['💥','⭐','🫧','🎯','🎪'],
    borderRadius: '0.25rem',
    buttonStyle: 'rounded border-2 border-black font-black shadow-[4px_4px_0px_black]',
  },
  {
    id: 'unicorn_dream',
    name: 'Unicorn Dream',
    category: 'kids',
    emoji: '🦄',
    description: 'Pastel rainbow, glitter effects, magical unicorn theme',
    preview: ['#ffd1dc','#b5eaff','#d4b3ff'],
    css: {
      '--primary': '320 80% 70%',
      '--secondary': '200 80% 75%',
      '--accent': '270 70% 75%',
      '--background': '300 100% 98%',
      '--foreground': '270 40% 30%',
    },
    nav: { style: 'rainbow', bg: 'linear-gradient(135deg, #ffd1dc, #b5eaff, #d4b3ff)', textColor: '#7b2d8b', logoColor: '#e91e63' },
    hero: { style: 'sparkle', bg: 'linear-gradient(135deg, #ffd1dc 0%, #d4b3ff 50%, #b5eaff 100%)', pattern: 'stars' },
    footer: { bg: '#7b2d8b', textColor: '#ffd1dc', accent: '#feca57' },
    decorations: ['🦄','🌈','✨','💜','🌸'],
    borderRadius: '3rem',
    buttonStyle: 'rounded-full font-bold shadow-lg bg-gradient-to-r from-pink-400 to-purple-400',
  },
  {
    id: 'dinosaur_bash',
    name: 'Dinosaur Bash',
    category: 'kids',
    emoji: '🦕',
    description: 'Jungle green, prehistoric adventure, playful typography',
    preview: ['#2d5016','#7bc67e','#ffd700'],
    css: {
      '--primary': '120 60% 30%',
      '--secondary': '120 40% 60%',
      '--accent': '45 100% 55%',
      '--background': '120 30% 96%',
      '--foreground': '120 30% 10%',
    },
    nav: { style: 'solid', bg: '#2d5016', textColor: '#7bc67e', logoColor: '#ffd700' },
    hero: { style: 'jungle', bg: 'linear-gradient(135deg, #2d5016 0%, #4a7c2f 50%, #2d5016 100%)', pattern: 'dots' },
    footer: { bg: '#1a2e0a', textColor: '#7bc67e', accent: '#ffd700' },
    decorations: ['🦕','🦖','🌿','🦎','⭐'],
    borderRadius: '0.75rem',
    buttonStyle: 'rounded-lg font-bold',
  },
  {
    id: 'superhero_party',
    name: 'Superhero Party',
    category: 'kids',
    emoji: '🦸',
    description: 'Bold primary colors, comic book halftone, action-packed',
    preview: ['#dc143c','#002fa7','#ffd700'],
    css: {
      '--primary': '348 82% 47%',
      '--secondary': '224 100% 33%',
      '--accent': '45 100% 50%',
      '--background': '0 0% 100%',
      '--foreground': '0 0% 5%',
    },
    nav: { style: 'bold-stripe', bg: '#dc143c', textColor: '#fff', logoColor: '#ffd700' },
    hero: { style: 'halftone', bg: 'linear-gradient(45deg, #dc143c, #002fa7)', pattern: 'dots' },
    footer: { bg: '#002fa7', textColor: '#fff', accent: '#ffd700' },
    decorations: ['⚡','💥','🦸','⭐','🌟'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded font-black uppercase tracking-widest',
  },
  {
    id: 'princess_palace',
    name: 'Princess Palace',
    category: 'kids',
    emoji: '👑',
    description: 'Pink and gold royalty, tiara decorations, elegant for girls',
    preview: ['#ff69b4','#ffd700','#fff0f5'],
    css: {
      '--primary': '330 100% 65%',
      '--secondary': '45 100% 50%',
      '--accent': '330 60% 85%',
      '--background': '330 100% 98%',
      '--foreground': '330 30% 20%',
    },
    nav: { style: 'elegant', bg: 'linear-gradient(135deg, #ff69b4, #ffd700)', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'royal', bg: 'linear-gradient(135deg, #ff69b4 0%, #ffd700 50%, #ff69b4 100%)', pattern: null },
    footer: { bg: '#330020', textColor: '#ffd700', accent: '#ff69b4' },
    decorations: ['👑','💎','🌸','✨','🎀'],
    borderRadius: '2.5rem',
    buttonStyle: 'rounded-full font-bold shadow-xl',
  },
  {
    id: 'space_explorer',
    name: 'Space Explorer',
    category: 'kids',
    emoji: '🚀',
    description: 'Deep space dark, stars, planets, cosmic adventure',
    preview: ['#0b0c2a','#6c5ce7','#00d2ff'],
    css: {
      '--primary': '250 80% 65%',
      '--secondary': '190 100% 50%',
      '--accent': '45 100% 60%',
      '--background': '235 60% 8%',
      '--foreground': '0 0% 95%',
    },
    nav: { style: 'glassmorphism', bg: 'rgba(11,12,42,0.85)', textColor: '#00d2ff', logoColor: '#6c5ce7' },
    hero: { style: 'cosmic', bg: 'linear-gradient(135deg, #0b0c2a 0%, #1a1a4e 50%, #0b0c2a 100%)', pattern: 'stars' },
    footer: { bg: '#070716', textColor: '#6c5ce7', accent: '#00d2ff' },
    decorations: ['🚀','⭐','🌙','🪐','✨'],
    borderRadius: '1rem',
    buttonStyle: 'rounded-lg font-bold border border-blue-400/30',
  },
  {
    id: 'circus_fun',
    name: 'Circus Fun',
    category: 'kids',
    emoji: '🎪',
    description: 'Red and white stripes, circus tent, big top energy',
    preview: ['#dc143c','#fff','#ffd700'],
    css: {
      '--primary': '348 82% 45%',
      '--secondary': '45 100% 50%',
      '--accent': '25 100% 55%',
      '--background': '0 0% 100%',
      '--foreground': '0 0% 10%',
    },
    nav: { style: 'striped', bg: 'repeating-linear-gradient(45deg, #dc143c 0px, #dc143c 20px, #fff 20px, #fff 40px)', textColor: '#ffd700', logoColor: '#ffd700' },
    hero: { style: 'tent', bg: 'linear-gradient(135deg, #dc143c, #fff, #dc143c)', pattern: 'dots' },
    footer: { bg: '#dc143c', textColor: '#fff', accent: '#ffd700' },
    decorations: ['🎪','🤹','🎠','🎡','🎢'],
    borderRadius: '1rem',
    buttonStyle: 'rounded-full font-bold bg-yellow-400 text-red-700',
  },
  {
    id: 'candyland',
    name: 'Candyland',
    category: 'kids',
    emoji: '🍭',
    description: 'Sweet candy colors, lollipops, sugar rush vibes',
    preview: ['#ff6eb4','#ff9b42','#7ee8a2'],
    css: {
      '--primary': '330 100% 65%',
      '--secondary': '25 100% 63%',
      '--accent': '145 70% 60%',
      '--background': '340 100% 97%',
      '--foreground': '270 30% 20%',
    },
    nav: { style: 'candy', bg: 'linear-gradient(90deg, #ff6eb4, #ff9b42, #7ee8a2)', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'sweet', bg: 'linear-gradient(135deg, #ff6eb4, #ff9b42)', pattern: 'dots' },
    footer: { bg: '#7b1fa2', textColor: '#fff', accent: '#ff9b42' },
    decorations: ['🍭','🍬','🍩','🧁','🎂'],
    borderRadius: '3rem',
    buttonStyle: 'rounded-full font-bold text-white shadow-lg',
  },

  // ===== WEDDING =====
  {
    id: 'garden_romance',
    name: 'Garden Romance',
    category: 'wedding',
    emoji: '🌸',
    description: 'Soft blush and sage, floral elegance, botanical luxury',
    preview: ['#f2d6d8','#8fbc8f','#d4af7a'],
    css: {
      '--primary': '350 40% 70%',
      '--secondary': '120 30% 55%',
      '--accent': '38 45% 65%',
      '--background': '350 40% 98%',
      '--foreground': '0 20% 20%',
    },
    nav: { style: 'transparent-elegant', bg: 'rgba(255,255,255,0.85)', textColor: '#6b4c4c', logoColor: '#c4857a' },
    hero: { style: 'floral', bg: 'linear-gradient(135deg, #f2d6d8 0%, #e8f5e9 50%, #f2d6d8 100%)', pattern: null },
    footer: { bg: '#4a2c2c', textColor: '#f2d6d8', accent: '#d4af7a' },
    decorations: ['🌸','🌺','💐','🍃','✨'],
    borderRadius: '0.25rem',
    buttonStyle: 'rounded-full font-semibold tracking-wide',
  },
  {
    id: 'black_tie',
    name: 'Black Tie Luxury',
    category: 'wedding',
    emoji: '🖤',
    description: 'Monochrome luxury, gold accents, serif typography, ultra-elegant',
    preview: ['#1a1a1a','#c9a84c','#fff'],
    css: {
      '--primary': '38 55% 55%',
      '--secondary': '0 0% 90%',
      '--accent': '38 55% 45%',
      '--background': '0 0% 100%',
      '--foreground': '0 0% 8%',
    },
    nav: { style: 'serif-bar', bg: '#1a1a1a', textColor: '#c9a84c', logoColor: '#c9a84c' },
    hero: { style: 'luxury', bg: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%)', pattern: null },
    footer: { bg: '#0a0a0a', textColor: '#c9a84c', accent: '#c9a84c' },
    decorations: ['💎','🥂','✨','🖤','🪷'],
    borderRadius: '0.1rem',
    buttonStyle: 'rounded-none font-semibold tracking-widest uppercase border border-current',
  },
  {
    id: 'boho_chic',
    name: 'Boho Chic',
    category: 'wedding',
    emoji: '🌿',
    description: 'Terracotta, cream, macramé textures, free-spirit earthy vibe',
    preview: ['#c96e3a','#f5e6d3','#6b7c52'],
    css: {
      '--primary': '22 58% 50%',
      '--secondary': '80 25% 55%',
      '--accent': '35 60% 75%',
      '--background': '35 50% 97%',
      '--foreground': '22 30% 18%',
    },
    nav: { style: 'earthy', bg: '#f5e6d3', textColor: '#c96e3a', logoColor: '#c96e3a' },
    hero: { style: 'boho', bg: 'linear-gradient(135deg, #f5e6d3 0%, #e8d5b7 100%)', pattern: null },
    footer: { bg: '#3d2c1e', textColor: '#f5e6d3', accent: '#c96e3a' },
    decorations: ['🌿','🍃','🌾','✨','🪶'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded font-semibold',
  },
  {
    id: 'fairy_tale',
    name: 'Fairy Tale',
    category: 'wedding',
    emoji: '🏰',
    description: 'Purple and silver enchanted castle, magical evening celebration',
    preview: ['#4a0e8f','#c0c0c0','#ffe4e1'],
    css: {
      '--primary': '270 80% 35%',
      '--secondary': '0 0% 75%',
      '--accent': '320 60% 80%',
      '--background': '270 40% 97%',
      '--foreground': '270 30% 15%',
    },
    nav: { style: 'regal', bg: '#4a0e8f', textColor: '#c0c0c0', logoColor: '#ffe4e1' },
    hero: { style: 'enchanted', bg: 'linear-gradient(135deg, #4a0e8f 0%, #7b2d8b 50%, #4a0e8f 100%)', pattern: 'stars' },
    footer: { bg: '#1a0050', textColor: '#c0c0c0', accent: '#ffe4e1' },
    decorations: ['🏰','✨','💜','🌙','🪄'],
    borderRadius: '1.5rem',
    buttonStyle: 'rounded-full font-semibold',
  },
  {
    id: 'modern_minimalist_wedding',
    name: 'Modern Minimalist',
    category: 'wedding',
    emoji: '⬜',
    description: 'Clean white, minimal lines, sophisticated simplicity',
    preview: ['#fff','#e0e0e0','#2c2c2c'],
    css: {
      '--primary': '0 0% 15%',
      '--secondary': '0 0% 85%',
      '--accent': '0 0% 45%',
      '--background': '0 0% 100%',
      '--foreground': '0 0% 10%',
    },
    nav: { style: 'minimal', bg: '#fff', textColor: '#2c2c2c', logoColor: '#2c2c2c' },
    hero: { style: 'clean', bg: '#fafafa', pattern: null },
    footer: { bg: '#2c2c2c', textColor: '#fff', accent: '#e0e0e0' },
    decorations: ['○','◇','△','—','·'],
    borderRadius: '0.25rem',
    buttonStyle: 'rounded-none font-light tracking-widest uppercase border border-current',
  },

  // ===== BABY SHOWER =====
  {
    id: 'baby_blue_dream',
    name: 'Baby Blue Dream',
    category: 'baby_shower',
    emoji: '👶',
    description: 'Soft sky blue, clouds, stars — perfect for baby boy',
    preview: ['#87ceeb','#e0f7fa','#fff9c4'],
    css: {
      '--primary': '200 80% 65%',
      '--secondary': '185 70% 88%',
      '--accent': '45 100% 80%',
      '--background': '200 70% 97%',
      '--foreground': '200 40% 20%',
    },
    nav: { style: 'cloud', bg: 'rgba(135,206,235,0.9)', textColor: '#1565c0', logoColor: '#1565c0' },
    hero: { style: 'cloud', bg: 'linear-gradient(180deg, #87ceeb 0%, #e0f7fa 100%)', pattern: 'dots' },
    footer: { bg: '#1565c0', textColor: '#e0f7fa', accent: '#fff9c4' },
    decorations: ['☁️','⭐','🌙','👶','💙'],
    borderRadius: '2rem',
    buttonStyle: 'rounded-full font-semibold shadow',
  },
  {
    id: 'pink_bliss',
    name: 'Pink Bliss',
    category: 'baby_shower',
    emoji: '🌸',
    description: 'Blush pink, gold, flowers — sweet baby girl theme',
    preview: ['#f8a5c2','#ffeaa7','#fff0f5'],
    css: {
      '--primary': '340 80% 70%',
      '--secondary': '45 100% 70%',
      '--accent': '320 60% 85%',
      '--background': '340 100% 98%',
      '--foreground': '330 30% 20%',
    },
    nav: { style: 'soft', bg: 'rgba(248,165,194,0.9)', textColor: '#880e4f', logoColor: '#880e4f' },
    hero: { style: 'soft-pink', bg: 'linear-gradient(135deg, #f8a5c2 0%, #ffeaa7 100%)', pattern: null },
    footer: { bg: '#880e4f', textColor: '#f8a5c2', accent: '#ffeaa7' },
    decorations: ['🌸','🦋','💕','🌷','✨'],
    borderRadius: '2.5rem',
    buttonStyle: 'rounded-full font-semibold shadow-lg',
  },
  {
    id: 'gender_neutral',
    name: 'Gender Neutral',
    category: 'baby_shower',
    emoji: '🌈',
    description: 'Sage, mustard, neutral tones — modern and inclusive',
    preview: ['#8fbc8f','#f0c040','#d4b896'],
    css: {
      '--primary': '120 30% 55%',
      '--secondary': '45 80% 60%',
      '--accent': '30 40% 65%',
      '--background': '40 30% 97%',
      '--foreground': '30 30% 15%',
    },
    nav: { style: 'natural', bg: '#8fbc8f', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'natural', bg: 'linear-gradient(135deg, #8fbc8f 0%, #f0c040 100%)', pattern: null },
    footer: { bg: '#3d5c3d', textColor: '#f0c040', accent: '#d4b896' },
    decorations: ['🌿','🦒','🌾','⭐','🐸'],
    borderRadius: '1rem',
    buttonStyle: 'rounded-full font-semibold',
  },

  // ===== CORPORATE / OFFICE =====
  {
    id: 'corporate_clean',
    name: 'Corporate Clean',
    category: 'corporate',
    emoji: '🏢',
    description: 'Navy and white, professional, trust-building business aesthetic',
    preview: ['#003087','#fff','#f0f4ff'],
    css: {
      '--primary': '220 100% 27%',
      '--secondary': '220 50% 95%',
      '--accent': '210 80% 50%',
      '--background': '220 30% 98%',
      '--foreground': '220 30% 12%',
    },
    nav: { style: 'corporate', bg: '#003087', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'business', bg: 'linear-gradient(135deg, #003087 0%, #0066cc 100%)', pattern: null },
    footer: { bg: '#001a4d', textColor: '#fff', accent: '#4da6ff' },
    decorations: ['🏢','📊','💼','🎯','✅'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded font-semibold',
  },
  {
    id: 'tech_modern',
    name: 'Tech Modern',
    category: 'corporate',
    emoji: '💻',
    description: 'Dark mode, electric blue accents, sleek and futuristic',
    preview: ['#0a0a1a','#00d4ff','#7c3aed'],
    css: {
      '--primary': '195 100% 50%',
      '--secondary': '270 80% 55%',
      '--accent': '150 100% 45%',
      '--background': '235 50% 6%',
      '--foreground': '0 0% 95%',
    },
    nav: { style: 'dark-tech', bg: 'rgba(10,10,26,0.9)', textColor: '#00d4ff', logoColor: '#7c3aed' },
    hero: { style: 'tech', bg: 'linear-gradient(135deg, #0a0a1a 0%, #1a0a3a 100%)', pattern: 'grid' },
    footer: { bg: '#050510', textColor: '#00d4ff', accent: '#7c3aed' },
    decorations: ['💻','⚡','🌐','🔮','✦'],
    borderRadius: '0.375rem',
    buttonStyle: 'rounded font-bold tracking-wide',
  },
  {
    id: 'startup_bold',
    name: 'Startup Bold',
    category: 'corporate',
    emoji: '🚀',
    description: 'Vibrant purple and coral, dynamic startup energy',
    preview: ['#5c37d5','#ff6b6b','#fff'],
    css: {
      '--primary': '255 65% 52%',
      '--secondary': '0 100% 70%',
      '--accent': '160 60% 45%',
      '--background': '0 0% 100%',
      '--foreground': '255 30% 10%',
    },
    nav: { style: 'gradient-nav', bg: 'linear-gradient(90deg, #5c37d5, #ff6b6b)', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'bold-startup', bg: 'linear-gradient(135deg, #5c37d5 0%, #ff6b6b 100%)', pattern: null },
    footer: { bg: '#1e0a5c', textColor: '#fff', accent: '#ff6b6b' },
    decorations: ['🚀','💡','🎯','⚡','🌟'],
    borderRadius: '0.75rem',
    buttonStyle: 'rounded-lg font-bold shadow-lg',
  },
  {
    id: 'real_estate_elegant',
    name: 'Real Estate Elegant',
    category: 'corporate',
    emoji: '🏠',
    description: 'Charcoal, warm gold, sophisticated property feel',
    preview: ['#2c2c2c','#c9a84c','#f5f5f0'],
    css: {
      '--primary': '38 55% 53%',
      '--secondary': '0 0% 17%',
      '--accent': '38 40% 40%',
      '--background': '50 30% 97%',
      '--foreground': '0 0% 10%',
    },
    nav: { style: 'premium', bg: '#2c2c2c', textColor: '#c9a84c', logoColor: '#c9a84c' },
    hero: { style: 'premium', bg: 'linear-gradient(135deg, #2c2c2c 0%, #4a4a4a 100%)', pattern: null },
    footer: { bg: '#1a1a1a', textColor: '#c9a84c', accent: '#f5f5f0' },
    decorations: ['🏠','🔑','💎','✦','🌿'],
    borderRadius: '0.25rem',
    buttonStyle: 'rounded font-semibold tracking-wider',
  },

  // ===== GRADUATION =====
  {
    id: 'graduation_gold',
    name: 'Graduation Gold',
    category: 'graduation',
    emoji: '🎓',
    description: 'Deep navy and gold, achievement, cap and diploma vibes',
    preview: ['#1a237e','#ffd700','#fff'],
    css: {
      '--primary': '231 70% 35%',
      '--secondary': '45 100% 50%',
      '--accent': '0 0% 95%',
      '--background': '0 0% 100%',
      '--foreground': '231 30% 10%',
    },
    nav: { style: 'academic', bg: '#1a237e', textColor: '#ffd700', logoColor: '#ffd700' },
    hero: { style: 'graduation', bg: 'linear-gradient(135deg, #1a237e 0%, #283593 100%)', pattern: 'stars' },
    footer: { bg: '#0d1257', textColor: '#ffd700', accent: '#fff' },
    decorations: ['🎓','📜','⭐','🏆','🎉'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded font-bold',
  },
  {
    id: 'class_of_2026',
    name: 'Class of 2026',
    category: 'graduation',
    emoji: '🏆',
    description: 'Black and gold, bold typography, milestone celebration',
    preview: ['#1a1a1a','#ffd700','#fff'],
    css: {
      '--primary': '45 100% 50%',
      '--secondary': '0 0% 90%',
      '--accent': '45 80% 60%',
      '--background': '0 0% 100%',
      '--foreground': '0 0% 5%',
    },
    nav: { style: 'bold-dark', bg: '#1a1a1a', textColor: '#ffd700', logoColor: '#ffd700' },
    hero: { style: 'milestone', bg: 'linear-gradient(135deg, #1a1a1a 0%, #333 100%)', pattern: 'stars' },
    footer: { bg: '#0a0a0a', textColor: '#ffd700', accent: '#fff' },
    decorations: ['🏆','⭐','🎓','🥂','🌟'],
    borderRadius: '0.25rem',
    buttonStyle: 'rounded-none font-black uppercase tracking-widest',
  },

  // ===== HOLIDAY / SEASONAL =====
  {
    id: 'christmas_festive',
    name: 'Christmas Festive',
    category: 'holiday',
    emoji: '🎄',
    description: 'Traditional red and green, gold, classic Christmas magic',
    preview: ['#c41e3a','#2d5a27','#ffd700'],
    css: {
      '--primary': '350 75% 44%',
      '--secondary': '120 40% 27%',
      '--accent': '45 100% 50%',
      '--background': '0 0% 100%',
      '--foreground': '0 0% 8%',
    },
    nav: { style: 'festive', bg: '#c41e3a', textColor: '#fff', logoColor: '#ffd700' },
    hero: { style: 'christmas', bg: 'linear-gradient(135deg, #c41e3a 0%, #2d5a27 100%)', pattern: 'stars' },
    footer: { bg: '#1a0f0f', textColor: '#ffd700', accent: '#c41e3a' },
    decorations: ['🎄','⭐','🎅','❄️','🎁'],
    borderRadius: '1rem',
    buttonStyle: 'rounded-full font-bold',
  },
  {
    id: 'winter_wonderland',
    name: 'Winter Wonderland',
    category: 'holiday',
    emoji: '❄️',
    description: 'Ice blue and silver, snowflakes, magical winter atmosphere',
    preview: ['#b3e5fc','#e1f5fe','#78909c'],
    css: {
      '--primary': '200 90% 60%',
      '--secondary': '200 60% 80%',
      '--accent': '0 0% 60%',
      '--background': '200 60% 97%',
      '--foreground': '200 30% 15%',
    },
    nav: { style: 'ice', bg: 'rgba(179,229,252,0.9)', textColor: '#0277bd', logoColor: '#0277bd' },
    hero: { style: 'winter', bg: 'linear-gradient(180deg, #b3e5fc 0%, #e1f5fe 100%)', pattern: 'dots' },
    footer: { bg: '#01579b', textColor: '#b3e5fc', accent: '#fff' },
    decorations: ['❄️','⛄','🌨️','💎','✨'],
    borderRadius: '1.5rem',
    buttonStyle: 'rounded-full font-semibold shadow',
  },
  {
    id: 'halloween_spooky',
    name: 'Halloween Spooky',
    category: 'holiday',
    emoji: '🎃',
    description: 'Orange and black, spooky fun, halloween balloons galore',
    preview: ['#ff6600','#1a1a1a','#9c27b0'],
    css: {
      '--primary': '24 100% 50%',
      '--secondary': '270 60% 50%',
      '--accent': '45 100% 50%',
      '--background': '270 20% 8%',
      '--foreground': '0 0% 95%',
    },
    nav: { style: 'dark-orange', bg: '#1a1a1a', textColor: '#ff6600', logoColor: '#ff6600' },
    hero: { style: 'spooky', bg: 'linear-gradient(135deg, #1a1a1a 0%, #2d0050 100%)', pattern: 'stars' },
    footer: { bg: '#0a0a0a', textColor: '#ff6600', accent: '#9c27b0' },
    decorations: ['🎃','👻','🕷️','🦇','🌙'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded-lg font-bold',
  },
  {
    id: 'new_years_glam',
    name: "New Year's Glam",
    category: 'holiday',
    emoji: '🥂',
    description: 'Black and gold glitter, NYE sophistication, countdown ready',
    preview: ['#0a0a0a','#c9a84c','#fff'],
    css: {
      '--primary': '45 80% 55%',
      '--secondary': '0 0% 90%',
      '--accent': '45 60% 45%',
      '--background': '0 0% 5%',
      '--foreground': '0 0% 95%',
    },
    nav: { style: 'glamour', bg: 'rgba(10,10,10,0.95)', textColor: '#c9a84c', logoColor: '#c9a84c' },
    hero: { style: 'glamour', bg: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)', pattern: 'stars' },
    footer: { bg: '#050505', textColor: '#c9a84c', accent: '#fff' },
    decorations: ['🥂','✨','🎊','🌟','💫'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded-full font-bold border border-yellow-400/50',
  },

  // ===== FUN / PARTY =====
  {
    id: 'festival_vibes',
    name: 'Festival Vibes',
    category: 'fun',
    emoji: '🎡',
    description: 'Bold multi-color, music festival energy, unstoppable fun',
    preview: ['#ff0080','#00ff80','#8000ff'],
    css: {
      '--primary': '320 100% 50%',
      '--secondary': '150 100% 50%',
      '--accent': '270 100% 50%',
      '--background': '0 0% 5%',
      '--foreground': '0 0% 98%',
    },
    nav: { style: 'festival', bg: 'linear-gradient(90deg, #ff0080, #8000ff)', textColor: '#fff', logoColor: '#00ff80' },
    hero: { style: 'festival', bg: 'linear-gradient(135deg, #ff0080, #8000ff, #00ff80)', pattern: 'dots' },
    footer: { bg: '#000', textColor: '#ff0080', accent: '#00ff80' },
    decorations: ['🎡','🎢','🎠','🎶','💥'],
    borderRadius: '0.75rem',
    buttonStyle: 'rounded-full font-black',
  },
  {
    id: 'tropical_luau',
    name: 'Tropical Luau',
    category: 'fun',
    emoji: '🌺',
    description: 'Vibrant tropical colors, hibiscus, beach party spirit',
    preview: ['#ff4d6d','#06d6a0','#ffd166'],
    css: {
      '--primary': '349 100% 65%',
      '--secondary': '164 90% 43%',
      '--accent': '42 100% 70%',
      '--background': '45 100% 97%',
      '--foreground': '180 30% 10%',
    },
    nav: { style: 'tropical', bg: 'linear-gradient(90deg, #ff4d6d, #06d6a0)', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'tropical', bg: 'linear-gradient(135deg, #ff4d6d 0%, #ffd166 50%, #06d6a0 100%)', pattern: null },
    footer: { bg: '#003d2c', textColor: '#06d6a0', accent: '#ffd166' },
    decorations: ['🌺','🌴','🌊','🍍','🦜'],
    borderRadius: '2rem',
    buttonStyle: 'rounded-full font-bold shadow-lg',
  },
  {
    id: 'retro_disco',
    name: 'Retro Disco',
    category: 'fun',
    emoji: '🕺',
    description: 'Groovy 70s colors, mirror ball, retro typography',
    preview: ['#ff6b35','#f7c59f','#efefd0'],
    css: {
      '--primary': '22 100% 60%',
      '--secondary': '37 90% 78%',
      '--accent': '55 80% 88%',
      '--background': '55 50% 96%',
      '--foreground': '22 30% 10%',
    },
    nav: { style: 'retro', bg: '#ff6b35', textColor: '#fff', logoColor: '#f7c59f' },
    hero: { style: 'disco', bg: 'linear-gradient(135deg, #ff6b35, #f7c59f)', pattern: 'dots' },
    footer: { bg: '#1a0a00', textColor: '#ff6b35', accent: '#f7c59f' },
    decorations: ['🕺','💿','🎵','✨','🌟'],
    borderRadius: '0.25rem',
    buttonStyle: 'rounded font-bold uppercase',
  },
  {
    id: 'mermaid_magic',
    name: 'Mermaid Magic',
    category: 'fun',
    emoji: '🧜',
    description: 'Ocean teal, coral, iridescent scales, underwater fantasy',
    preview: ['#006d77','#83c5be','#f7a072'],
    css: {
      '--primary': '184 90% 23%',
      '--secondary': '178 40% 64%',
      '--accent': '17 85% 70%',
      '--background': '184 60% 97%',
      '--foreground': '184 40% 10%',
    },
    nav: { style: 'ocean', bg: '#006d77', textColor: '#83c5be', logoColor: '#f7a072' },
    hero: { style: 'ocean', bg: 'linear-gradient(135deg, #006d77 0%, #83c5be 100%)', pattern: null },
    footer: { bg: '#003a40', textColor: '#83c5be', accent: '#f7a072' },
    decorations: ['🧜','🐚','🌊','💎','🦋'],
    borderRadius: '2rem',
    buttonStyle: 'rounded-full font-semibold',
  },
  {
    id: 'tie_dye',
    name: 'Tie Dye Groovy',
    category: 'fun',
    emoji: '🌀',
    description: 'Swirling tie-dye colors, hippie peace, 60s flower power',
    preview: ['#ff6b6b','#ffd93d','#6bcb77'],
    css: {
      '--primary': '0 100% 70%',
      '--secondary': '45 100% 55%',
      '--accent': '130 55% 57%',
      '--background': '45 100% 97%',
      '--foreground': '0 30% 10%',
    },
    nav: { style: 'tie-dye', bg: 'linear-gradient(90deg, #ff6b6b, #ffd93d, #6bcb77, #4d96ff)', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'swirl', bg: 'conic-gradient(#ff6b6b, #ffd93d, #6bcb77, #4d96ff, #ff6b6b)', pattern: null },
    footer: { bg: '#1a0a00', textColor: '#ffd93d', accent: '#ff6b6b' },
    decorations: ['🌀','✌️','🌸','☮️','🌈'],
    borderRadius: '3rem',
    buttonStyle: 'rounded-full font-bold',
  },

  // ===== SEASONAL / SPRING-SUMMER =====
  {
    id: 'spring_blossom',
    name: 'Spring Blossom',
    category: 'seasonal',
    emoji: '🌷',
    description: 'Fresh spring colors, cherry blossoms, renewal energy',
    preview: ['#ff9a9e','#a18cd1','#ffecd2'],
    css: {
      '--primary': '349 100% 80%',
      '--secondary': '263 50% 73%',
      '--accent': '35 100% 90%',
      '--background': '0 0% 100%',
      '--foreground': '263 30% 20%',
    },
    nav: { style: 'spring', bg: 'rgba(255,255,255,0.92)', textColor: '#a18cd1', logoColor: '#ff9a9e' },
    hero: { style: 'spring', bg: 'linear-gradient(135deg, #ff9a9e 0%, #ffecd2 100%)', pattern: null },
    footer: { bg: '#6a1b9a', textColor: '#ffecd2', accent: '#ff9a9e' },
    decorations: ['🌷','🌸','🌼','🦋','🐦'],
    borderRadius: '2rem',
    buttonStyle: 'rounded-full font-semibold',
  },
  {
    id: 'summer_breeze',
    name: 'Summer Breeze',
    category: 'seasonal',
    emoji: '☀️',
    description: 'Sunshine yellow, ocean blue, summer holiday fun',
    preview: ['#ffd700','#00b4d8','#ffffff'],
    css: {
      '--primary': '45 100% 50%',
      '--secondary': '197 100% 43%',
      '--accent': '25 100% 55%',
      '--background': '197 80% 97%',
      '--foreground': '197 40% 10%',
    },
    nav: { style: 'beach', bg: '#ffd700', textColor: '#00b4d8', logoColor: '#0077b6' },
    hero: { style: 'beach', bg: 'linear-gradient(135deg, #00b4d8 0%, #90e0ef 50%, #caf0f8 100%)', pattern: null },
    footer: { bg: '#023e8a', textColor: '#90e0ef', accent: '#ffd700' },
    decorations: ['☀️','🏖️','🌊','🌺','🍦'],
    borderRadius: '1.5rem',
    buttonStyle: 'rounded-full font-bold shadow',
  },
  {
    id: 'autumn_harvest',
    name: 'Autumn Harvest',
    category: 'seasonal',
    emoji: '🍁',
    description: 'Rich autumn tones, pumpkins, cozy warm ambiance',
    preview: ['#d2691e','#ff8c00','#8b4513'],
    css: {
      '--primary': '20 65% 45%',
      '--secondary': '30 100% 50%',
      '--accent': '45 80% 55%',
      '--background': '35 60% 96%',
      '--foreground': '20 40% 10%',
    },
    nav: { style: 'earthy', bg: '#8b4513', textColor: '#ffd700', logoColor: '#ffd700' },
    hero: { style: 'autumn', bg: 'linear-gradient(135deg, #d2691e 0%, #ff8c00 100%)', pattern: null },
    footer: { bg: '#4a1500', textColor: '#ff8c00', accent: '#ffd700' },
    decorations: ['🍁','🎃','🌰','🍂','🍎'],
    borderRadius: '0.75rem',
    buttonStyle: 'rounded-lg font-semibold',
  },

  // ===== LUXURY / HIGH-END =====
  {
    id: 'champagne_gold',
    name: 'Champagne & Gold',
    category: 'luxury',
    emoji: '🥂',
    description: 'Warm champagne, brushed gold, ultra-premium events',
    preview: ['#f5e6c8','#c9a84c','#2c1810'],
    css: {
      '--primary': '38 55% 53%',
      '--secondary': '35 40% 80%',
      '--accent': '38 40% 40%',
      '--background': '38 60% 97%',
      '--foreground': '20 30% 10%',
    },
    nav: { style: 'luxury', bg: 'rgba(245,230,200,0.95)', textColor: '#c9a84c', logoColor: '#8b6914' },
    hero: { style: 'luxury', bg: 'linear-gradient(135deg, #f5e6c8 0%, #c9a84c 100%)', pattern: null },
    footer: { bg: '#2c1810', textColor: '#c9a84c', accent: '#f5e6c8' },
    decorations: ['🥂','💎','✨','🌹','🕯️'],
    borderRadius: '0.1rem',
    buttonStyle: 'rounded-none tracking-widest uppercase font-semibold border border-yellow-700',
  },
  {
    id: 'marble_luxe',
    name: 'Marble Luxe',
    category: 'luxury',
    emoji: '🪨',
    description: 'White marble, black veins, gold — architectural luxury',
    preview: ['#f5f5f5','#1a1a1a','#c9a84c'],
    css: {
      '--primary': '0 0% 10%',
      '--secondary': '38 55% 53%',
      '--accent': '0 0% 60%',
      '--background': '0 0% 98%',
      '--foreground': '0 0% 8%',
    },
    nav: { style: 'marble', bg: 'rgba(245,245,245,0.95)', textColor: '#1a1a1a', logoColor: '#c9a84c' },
    hero: { style: 'marble', bg: 'linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 100%)', pattern: null },
    footer: { bg: '#1a1a1a', textColor: '#c9a84c', accent: '#f5f5f5' },
    decorations: ['◇','✦','◈','⬡','—'],
    borderRadius: '0',
    buttonStyle: 'rounded-none font-light tracking-widest uppercase border',
  },

  // ===== WHIMSICAL / ARTISTIC =====
  {
    id: 'watercolor_dreams',
    name: 'Watercolor Dreams',
    category: 'artistic',
    emoji: '🎨',
    description: 'Soft watercolor washes, artistic strokes, painterly feel',
    preview: ['#f8c8dc','#c8dcf8','#dcf8c8'],
    css: {
      '--primary': '340 70% 70%',
      '--secondary': '210 70% 75%',
      '--accent': '130 70% 70%',
      '--background': '60 60% 98%',
      '--foreground': '270 30% 20%',
    },
    nav: { style: 'watercolor', bg: 'rgba(248,200,220,0.9)', textColor: '#6b2d5e', logoColor: '#e91e63' },
    hero: { style: 'watercolor', bg: 'linear-gradient(135deg, #f8c8dc 0%, #c8dcf8 50%, #dcf8c8 100%)', pattern: null },
    footer: { bg: '#2d1b4e', textColor: '#f8c8dc', accent: '#c8dcf8' },
    decorations: ['🎨','🖌️','🌈','💜','✨'],
    borderRadius: '1.5rem',
    buttonStyle: 'rounded-full font-semibold',
  },
  {
    id: 'art_deco',
    name: 'Art Deco Glam',
    category: 'artistic',
    emoji: '🔺',
    description: 'Geometric 1920s Art Deco, gold on black, gatsby glamour',
    preview: ['#1a1209','#c9a84c','#e8d5b7'],
    css: {
      '--primary': '38 70% 50%',
      '--secondary': '38 50% 75%',
      '--accent': '38 40% 35%',
      '--background': '38 20% 8%',
      '--foreground': '38 50% 80%',
    },
    nav: { style: 'deco', bg: '#1a1209', textColor: '#c9a84c', logoColor: '#c9a84c' },
    hero: { style: 'deco', bg: 'linear-gradient(135deg, #1a1209 0%, #2c1f0a 100%)', pattern: 'grid' },
    footer: { bg: '#0a0806', textColor: '#c9a84c', accent: '#e8d5b7' },
    decorations: ['◆','▲','✦','◈','⬟'],
    borderRadius: '0',
    buttonStyle: 'rounded-none font-bold tracking-widest uppercase border-2 border-yellow-600',
  },
  {
    id: 'pastel_kawaii',
    name: 'Pastel Kawaii',
    category: 'artistic',
    emoji: '🌟',
    description: 'Japanese kawaii aesthetics, soft pastels, cute icons',
    preview: ['#ffd6e0','#c1fba4','#7bf1a8'],
    css: {
      '--primary': '349 100% 85%',
      '--secondary': '130 85% 81%',
      '--accent': '150 80% 74%',
      '--background': '300 100% 99%',
      '--foreground': '330 40% 25%',
    },
    nav: { style: 'kawaii', bg: 'rgba(255,214,224,0.95)', textColor: '#e91e63', logoColor: '#e91e63' },
    hero: { style: 'kawaii', bg: 'linear-gradient(135deg, #ffd6e0 0%, #c1fba4 100%)', pattern: 'dots' },
    footer: { bg: '#4a0050', textColor: '#ffd6e0', accent: '#c1fba4' },
    decorations: ['🌟','💗','🌸','🍡','⭐'],
    borderRadius: '3rem',
    buttonStyle: 'rounded-full font-bold text-sm',
  },

  // ===== SPECIALTY / UNIQUE =====
  {
    id: 'galaxy_swirl',
    name: 'Galaxy Swirl',
    category: 'specialty',
    emoji: '🌌',
    description: 'Deep space nebulas, cosmic color swirls, astronomy vibes',
    preview: ['#0f0c29','#302b63','#24243e'],
    css: {
      '--primary': '280 70% 65%',
      '--secondary': '200 100% 60%',
      '--accent': '45 100% 60%',
      '--background': '250 60% 6%',
      '--foreground': '0 0% 95%',
    },
    nav: { style: 'space', bg: 'rgba(15,12,41,0.9)', textColor: '#b39ddb', logoColor: '#e040fb' },
    hero: { style: 'nebula', bg: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)', pattern: 'stars' },
    footer: { bg: '#050310', textColor: '#b39ddb', accent: '#e040fb' },
    decorations: ['🌌','⭐','💫','🌙','✨'],
    borderRadius: '1rem',
    buttonStyle: 'rounded-lg font-bold',
  },
  {
    id: 'sports_champion',
    name: 'Sports Champion',
    category: 'specialty',
    emoji: '🏆',
    description: 'Athletic bold colors, stadium energy, championship celebration',
    preview: ['#1a237e','#ffd700','#e53935'],
    css: {
      '--primary': '348 75% 47%',
      '--secondary': '45 100% 50%',
      '--accent': '231 70% 35%',
      '--background': '0 0% 100%',
      '--foreground': '0 0% 5%',
    },
    nav: { style: 'sports', bg: '#1a237e', textColor: '#ffd700', logoColor: '#ffd700' },
    hero: { style: 'stadium', bg: 'linear-gradient(135deg, #e53935 0%, #1a237e 100%)', pattern: null },
    footer: { bg: '#0d1257', textColor: '#ffd700', accent: '#e53935' },
    decorations: ['🏆','🥇','⚡','🎯','🌟'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded font-black uppercase tracking-wide',
  },
  {
    id: 'pride_celebration',
    name: 'Pride Celebration',
    category: 'specialty',
    emoji: '🏳️🌈',
    description: 'All six rainbow colors, inclusive, joyful celebration',
    preview: ['#FF0018','#FFA52C','#FFFF41'],
    css: {
      '--primary': '0 100% 50%',
      '--secondary': '45 100% 55%',
      '--accent': '270 100% 60%',
      '--background': '0 0% 100%',
      '--foreground': '0 0% 5%',
    },
    nav: { style: 'pride', bg: 'linear-gradient(90deg, #FF0018, #FFA52C, #FFFF41, #008018, #0000F9, #86007D)', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'pride', bg: 'linear-gradient(135deg, #FF0018, #FFA52C, #FFFF41, #008018, #0000F9, #86007D)', pattern: null },
    footer: { bg: '#0a0a0a', textColor: '#FFA52C', accent: '#FFFF41' },
    decorations: ['🌈','🎉','💜','💛','❤️'],
    borderRadius: '2rem',
    buttonStyle: 'rounded-full font-bold',
  },
  {
    id: 'casino_royale',
    name: 'Casino Royale',
    category: 'specialty',
    emoji: '🃏',
    description: 'Vegas glamour, playing cards, red and black jackpot',
    preview: ['#1a0000','#dc143c','#ffd700'],
    css: {
      '--primary': '350 75% 45%',
      '--secondary': '45 100% 50%',
      '--accent': '0 0% 80%',
      '--background': '0 0% 5%',
      '--foreground': '0 0% 95%',
    },
    nav: { style: 'casino', bg: '#1a0000', textColor: '#ffd700', logoColor: '#ffd700' },
    hero: { style: 'casino', bg: 'linear-gradient(135deg, #1a0000 0%, #4a0000 100%)', pattern: 'stars' },
    footer: { bg: '#0a0000', textColor: '#ffd700', accent: '#dc143c' },
    decorations: ['🃏','🎰','💎','🥂','♠️'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded font-bold border border-yellow-500',
  },
  {
    id: 'garden_party',
    name: 'Garden Party',
    category: 'specialty',
    emoji: '🌻',
    description: 'Sunflower yellow, fresh greenery, outdoor celebration',
    preview: ['#ffd700','#228b22','#fff'],
    css: {
      '--primary': '45 100% 50%',
      '--secondary': '120 55% 27%',
      '--accent': '80 55% 55%',
      '--background': '80 30% 97%',
      '--foreground': '80 30% 10%',
    },
    nav: { style: 'garden', bg: '#228b22', textColor: '#ffd700', logoColor: '#ffd700' },
    hero: { style: 'garden', bg: 'linear-gradient(135deg, #ffd700 0%, #90ee90 100%)', pattern: null },
    footer: { bg: '#14531b', textColor: '#ffd700', accent: '#fff' },
    decorations: ['🌻','🌿','🦋','🌸','🐝'],
    borderRadius: '1.5rem',
    buttonStyle: 'rounded-full font-semibold shadow',
  },
  {
    id: 'ocean_breeze',
    name: 'Ocean Breeze',
    category: 'specialty',
    emoji: '🌊',
    description: 'Coastal blues, sea foam, nautical beach celebration',
    preview: ['#006994','#87ceeb','#f0f9ff'],
    css: {
      '--primary': '204 88% 30%',
      '--secondary': '200 60% 70%',
      '--accent': '190 100% 35%',
      '--background': '200 60% 97%',
      '--foreground': '204 40% 10%',
    },
    nav: { style: 'nautical', bg: '#006994', textColor: '#87ceeb', logoColor: '#fff' },
    hero: { style: 'ocean', bg: 'linear-gradient(180deg, #006994 0%, #87ceeb 50%, #f0f9ff 100%)', pattern: null },
    footer: { bg: '#003f5c', textColor: '#87ceeb', accent: '#ffd700' },
    decorations: ['🌊','⚓','🐚','🦀','⛵'],
    borderRadius: '1rem',
    buttonStyle: 'rounded-lg font-semibold',
  },
  {
    id: 'moroccan_nights',
    name: 'Moroccan Nights',
    category: 'specialty',
    emoji: '🕌',
    description: 'Rich jewel tones, geometric patterns, exotic celebration',
    preview: ['#8b0000','#ffd700','#1a0050'],
    css: {
      '--primary': '0 70% 27%',
      '--secondary': '45 100% 50%',
      '--accent': '270 80% 30%',
      '--background': '35 40% 97%',
      '--foreground': '0 30% 10%',
    },
    nav: { style: 'ornate', bg: '#8b0000', textColor: '#ffd700', logoColor: '#ffd700' },
    hero: { style: 'exotic', bg: 'linear-gradient(135deg, #8b0000 0%, #1a0050 100%)', pattern: 'stars' },
    footer: { bg: '#1a0000', textColor: '#ffd700', accent: '#c9a84c' },
    decorations: ['🕌','🌙','⭐','🌹','✨'],
    borderRadius: '0.5rem',
    buttonStyle: 'rounded font-bold',
  },
  {
    id: 'fiesta',
    name: 'Fiesta!',
    category: 'specialty',
    emoji: '🎉',
    description: 'Mexican fiesta colors, papel picado, vibrant celebration',
    preview: ['#e53935','#fdd835','#43a047'],
    css: {
      '--primary': '0 77% 56%',
      '--secondary': '47 98% 56%',
      '--accent': '122 43% 45%',
      '--background': '47 100% 97%',
      '--foreground': '0 40% 10%',
    },
    nav: { style: 'fiesta', bg: 'linear-gradient(90deg, #e53935, #fdd835, #43a047)', textColor: '#fff', logoColor: '#fff' },
    hero: { style: 'fiesta', bg: 'linear-gradient(135deg, #e53935, #fdd835)', pattern: 'dots' },
    footer: { bg: '#1a0000', textColor: '#fdd835', accent: '#e53935' },
    decorations: ['🎉','🌮','💃','🎊','🌺'],
    borderRadius: '1rem',
    buttonStyle: 'rounded-full font-bold',
  },

  // Additional themes to reach 100
  ...Array.from({ length: 44 }, (_, i) => {
    const extras = [
      { id: 'rose_quartz', name: 'Rose Quartz', cat: 'luxury', e: '🌹', p: ['#f48fb1','#f8bbd0','#fce4ec'], bg1: '#f48fb1', bg2: '#fce4ec' },
      { id: 'midnight_blue', name: 'Midnight Blue', cat: 'corporate', e: '🌙', p: ['#1a237e','#283593','#e8eaf6'], bg1: '#1a237e', bg2: '#283593' },
      { id: 'citrus_pop', name: 'Citrus Pop', cat: 'fun', e: '🍊', p: ['#ff6f00','#ffca28','#fff'], bg1: '#ff6f00', bg2: '#ffca28' },
      { id: 'sage_serenity', name: 'Sage & Serenity', cat: 'wedding', e: '🌿', p: ['#607d6a','#b2c4b2','#f5f0eb'], bg1: '#607d6a', bg2: '#b2c4b2' },
      { id: 'cherry_blossom', name: 'Cherry Blossom', cat: 'seasonal', e: '🌸', p: ['#f8bbd0','#e1bee7','#fff'], bg1: '#f8bbd0', bg2: '#e1bee7' },
      { id: 'electric_lime', name: 'Electric Lime', cat: 'fun', e: '⚡', p: ['#76ff03','#1a1a1a','#fff'], bg1: '#1a1a1a', bg2: '#33691e' },
      { id: 'dusty_rose', name: 'Dusty Rose', cat: 'wedding', e: '🥀', p: ['#c48b9f','#f7cad0','#eee'], bg1: '#c48b9f', bg2: '#f7cad0' },
      { id: 'jungle_wild', name: 'Jungle Wild', cat: 'kids', e: '🦁', p: ['#1b5e20','#ffd600','#795548'], bg1: '#1b5e20', bg2: '#ffd600' },
      { id: 'frozen_tundra', name: 'Frozen Tundra', cat: 'holiday', e: '🧊', p: ['#b3e5fc','#e1f5fe','#80deea'], bg1: '#b3e5fc', bg2: '#80deea' },
      { id: 'hot_pink', name: 'Hot Pink Glam', cat: 'fun', e: '💗', p: ['#e91e63','#f06292','#fce4ec'], bg1: '#e91e63', bg2: '#f06292' },
      { id: 'vintage_gold', name: 'Vintage Gold', cat: 'luxury', e: '🏺', p: ['#d4a017','#8b6914','#fdf6e3'], bg1: '#8b6914', bg2: '#d4a017' },
      { id: 'ocean_sunset', name: 'Ocean Sunset', cat: 'seasonal', e: '🌅', p: ['#ff7043','#ff8a65','#90caf9'], bg1: '#ff7043', bg2: '#90caf9' },
      { id: 'forest_moss', name: 'Forest & Moss', cat: 'baby_shower', e: '🌲', p: ['#2e7d32','#a5d6a7','#f1f8e9'], bg1: '#2e7d32', bg2: '#a5d6a7' },
      { id: 'bubblegum', name: 'Bubblegum', cat: 'kids', e: '🫧', p: ['#f48fb1','#ce93d8','#fff'], bg1: '#f48fb1', bg2: '#ce93d8' },
      { id: 'midnight_rose', name: 'Midnight Rose', cat: 'specialty', e: '🌹', p: ['#1a0020','#e91e63','#fff'], bg1: '#1a0020', bg2: '#e91e63' },
      { id: 'turquoise_dream', name: 'Turquoise Dream', cat: 'fun', e: '🩵', p: ['#00bcd4','#e0f7fa','#fff'], bg1: '#00bcd4', bg2: '#e0f7fa' },
      { id: 'velvet_plum', name: 'Velvet Plum', cat: 'luxury', e: '🟣', p: ['#4a148c','#7b1fa2','#e1bee7'], bg1: '#4a148c', bg2: '#7b1fa2' },
      { id: 'coral_paradise', name: 'Coral Paradise', cat: 'seasonal', e: '🪸', p: ['#ff6f61','#ffb347','#fff'], bg1: '#ff6f61', bg2: '#ffb347' },
      { id: 'starlight', name: 'Starlight', cat: 'specialty', e: '⭐', p: ['#1a237e','#ffd700','#fff'], bg1: '#0d1b3e', bg2: '#1a237e' },
      { id: 'peppermint', name: 'Peppermint Fresh', cat: 'holiday', e: '🍬', p: ['#e8f5e9','#e53935','#fff'], bg1: '#e53935', bg2: '#c8e6c9' },
      { id: 'neon_green', name: 'Neon Green', cat: 'fun', e: '🟢', p: ['#00e676','#1a1a1a','#69f0ae'], bg1: '#1a1a1a', bg2: '#1b5e20' },
      { id: 'lavender_haze', name: 'Lavender Haze', cat: 'wedding', e: '💜', p: ['#ce93d8','#e1bee7','#f3e5f5'], bg1: '#ce93d8', bg2: '#f3e5f5' },
      { id: 'tangerine', name: 'Tangerine Twist', cat: 'fun', e: '🍊', p: ['#ff6d00','#ff9e80','#fff'], bg1: '#ff6d00', bg2: '#ff9e80' },
      { id: 'blue_velvet', name: 'Blue Velvet', cat: 'luxury', e: '💙', p: ['#0d47a1','#1565c0','#e3f2fd'], bg1: '#0d47a1', bg2: '#1565c0' },
      { id: 'tropical_flamingo', name: 'Tropical Flamingo', cat: 'fun', e: '🦩', p: ['#e91e63','#ff6090','#fff'], bg1: '#e91e63', bg2: '#ff6090' },
      { id: 'nordic_cool', name: 'Nordic Cool', cat: 'corporate', e: '🌨️', p: ['#455a64','#b0bec5','#eceff1'], bg1: '#455a64', bg2: '#607d8b' },
      { id: 'golden_hour', name: 'Golden Hour', cat: 'seasonal', e: '🌇', p: ['#ffa000','#ff6f00','#fff'], bg1: '#ff6f00', bg2: '#ffa000' },
      { id: 'mint_cocoa', name: 'Mint & Cocoa', cat: 'baby_shower', e: '🍃', p: ['#80cbc4','#795548','#fff'], bg1: '#795548', bg2: '#80cbc4' },
      { id: 'carnival_colors', name: 'Carnival Colors', cat: 'kids', e: '🎡', p: ['#e53935','#fdd835','#1e88e5'], bg1: '#e53935', bg2: '#1e88e5' },
      { id: 'silver_lining', name: 'Silver Lining', cat: 'luxury', e: '🩶', p: ['#9e9e9e','#f5f5f5','#212121'], bg1: '#616161', bg2: '#9e9e9e' },
      { id: 'enchanted_forest', name: 'Enchanted Forest', cat: 'specialty', e: '🌳', p: ['#1b5e20','#7b1fa2','#ffd700'], bg1: '#1b5e20', bg2: '#7b1fa2' },
      { id: 'sunset_boulevard', name: 'Sunset Boulevard', cat: 'specialty', e: '🌆', p: ['#ff6b35','#f7c59f','#4a1942'], bg1: '#4a1942', bg2: '#ff6b35' },
      { id: 'sapphire_dreams', name: 'Sapphire Dreams', cat: 'luxury', e: '💎', p: ['#1565c0','#42a5f5','#e3f2fd'], bg1: '#0d47a1', bg2: '#1976d2' },
      { id: 'cranberry_fizz', name: 'Cranberry Fizz', cat: 'holiday', e: '🍷', p: ['#880e4f','#f48fb1','#fff'], bg1: '#880e4f', bg2: '#c2185b' },
      { id: 'peacock', name: 'Peacock Plume', cat: 'artistic', e: '🦚', p: ['#004d40','#00bfa5','#ffd740'], bg1: '#004d40', bg2: '#00897b' },
      { id: 'bluebell', name: 'Bluebell Meadow', cat: 'wedding', e: '🔵', p: ['#7986cb','#c5cae9','#fff'], bg1: '#5c6bc0', bg2: '#c5cae9' },
      { id: 'amber_glow', name: 'Amber Glow', cat: 'seasonal', e: '🕯️', p: ['#ff8f00','#ffca28','#fff8e1'], bg1: '#e65100', bg2: '#ff8f00' },
      { id: 'dusk_purple', name: 'Dusk Purple', cat: 'specialty', e: '🌆', p: ['#4a148c','#7c43bd','#ede7f6'], bg1: '#38006b', bg2: '#4a148c' },
      { id: 'sunshine_daydream', name: 'Sunshine Daydream', cat: 'kids', e: '☀️', p: ['#ffd600','#ff9800','#fff'], bg1: '#ff9800', bg2: '#ffd600' },
      { id: 'cotton_candy', name: 'Cotton Candy', cat: 'kids', e: '🍭', p: ['#f8bbd0','#e1bee7','#bbdefb'], bg1: '#f8bbd0', bg2: '#e1bee7' },
      { id: 'midnight_garden', name: 'Midnight Garden', cat: 'wedding', e: '🌙', p: ['#1a1a2e','#16213e','#0f3460'], bg1: '#1a1a2e', bg2: '#16213e' },
      { id: 'raspberry_sorbet', name: 'Raspberry Sorbet', cat: 'fun', e: '🍧', p: ['#e91e63','#ff80ab','#fff'], bg1: '#c2185b', bg2: '#e91e63' },
      { id: 'desert_sand', name: 'Desert Sand', cat: 'boho', e: '🏜️', p: ['#d4a76a','#b5835a','#f5deb3'], bg1: '#a0522d', bg2: '#d4a76a' },
      { id: 'indigo_night', name: 'Indigo Night', cat: 'specialty', e: '🌌', p: ['#1a237e','#3f51b5','#e8eaf6'], bg1: '#0d1257', bg2: '#1a237e' },
    ];
    const ex = extras[i % extras.length];
    return {
      id: `${ex.id}_v${Math.floor(i / extras.length) + 1}${i >= extras.length ? `_${i}` : ''}`,
      name: ex.name,
      category: ex.cat,
      emoji: ex.e,
      description: `${ex.name} theme with balloon-themed styling`,
      preview: ex.p,
      css: {
        '--primary': '340 82% 52%',
        '--secondary': '45 100% 60%',
        '--accent': '180 70% 48%',
        '--background': '0 0% 100%',
        '--foreground': '260 20% 16%',
      },
      nav: { style: 'default', bg: ex.bg1, textColor: '#fff', logoColor: '#fff' },
      hero: { style: 'default', bg: `linear-gradient(135deg, ${ex.bg1} 0%, ${ex.bg2} 100%)`, pattern: null },
      footer: { bg: ex.bg1, textColor: '#fff', accent: ex.p[1] },
      decorations: [ex.e, '🎈', '✨', '🎊', '🎉'],
      borderRadius: '1rem',
      buttonStyle: 'rounded-lg font-semibold',
    };
  }).slice(0, 44),
];

export const THEME_CATEGORIES = [
  { id: 'all', label: 'All Themes' },
  { id: 'kids', label: '🧒 Kids' },
  { id: 'wedding', label: '💒 Wedding' },
  { id: 'baby_shower', label: '👶 Baby Shower' },
  { id: 'corporate', label: '🏢 Corporate' },
  { id: 'graduation', label: '🎓 Graduation' },
  { id: 'holiday', label: '🎄 Holiday' },
  { id: 'fun', label: '🎉 Fun & Party' },
  { id: 'seasonal', label: '🌸 Seasonal' },
  { id: 'luxury', label: '💎 Luxury' },
  { id: 'artistic', label: '🎨 Artistic' },
  { id: 'specialty', label: '✨ Specialty' },
];

export function getThemeById(id) {
  return THEMES.find(t => t.id === id) || THEMES[0];
}